### ISSUE TITLE
is there any documetation for installing this package?

### ISSUE THREAD

**Issue by shokri-navid** [mattbrailsford/umbraco-photon#4]
I want to know how can I install this package on umbraco and is tis compatible with Umbraco 7 ?

**Comment by mattbrailsford** [comment]
@navid-dada unfortunately there are no docs at the moment as this is currently unreleased and so is provided "as is".

To install it though, you should be able to install the package file here https://github.com/mattbrailsford/umbraco-photon/tree/wip/media-picker/Package via the Umbraco back office, then it is configured as a data type. 

This uses Doc Types as blue prints, so you'll need to setup your doc type first before you configure your data types.

Hope this helps

Matt
